# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 424199319ca54892b3c30b7e91e26d61b8dae58c9e12412b23531a5fd5e4c584436bcde5d031637a21c80ec93596af5ab4b73945314266fd717c4bdd93aa20c1

test:
  secret_key_base: 98650d51b4aec3920b1b6a083943dbe0c5d4837d36a6dd34fd667619cfb86afeba9d71d227774f7eada66c2204f502430a41c7080884113af4707ad708d6a2a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
